export const SPECIALIZATIONS = {
  "Arts": [
    "Animation",
    "Anthropology",
    "Communication",
    "English Literature",
    "Fashion, Esthetics",
    "Fine Arts",
    "Food and Culinary",
    "Gender Studies",
    "General",
    "Geography",
    "Global Studies",
    "Graphic Design, Interior Design",
    "History",
    "Journalism",
    "Languages",
    "Liberal Arts",
    "Media, Photography, Film, Theatre, Performance",
    "Music, Audio",
    "Planning (Urban)",
    "Religion",
    "Sociology"
  ],
  "Business, Management and Economics": [
    "Accounting",
    "Entrepreneurship",
    "Finance, Economics",
    "Hospitality and Tourism, Recreation",
    "Human Resources",
    "International Business",
    "Management, Administration, General",
    "Marketing, Analyst, Advertising",
    "Public Relation",
    "Supply Chain"
  ],
  "Elementary and High School": [],
  "Engineering and Technology": [
    "Aero Space, Aviation and Pilot Technology",
    "Agriculture",
    "Architecture",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering, Construction",
    "Electrical Engineering",
    "Electronic",
    "Environmental Engineering",
    "Game Design, Game Animation, Game Creation",
    "General Engineering",
    "Industrial",
    "Material Engineering",
    "Mechanical, Manufacturing, Robotic Engineering",
    "Radiography",
    "Technology, Software, Computer, IT"
  ],
  "English for Academic Studies": [],
  "Health Sciences, Medicine, Nursing, Paramedic and Kinesiology": [],
  "Law, Politics, Social, Community Service and Teaching": [
    "Community, Social Service",
    "Law, Politics, Police, Security",
    "Teaching, Early Development, Child Care"
  ],
  "Sciences": [
    "Astronomy",
    "Biochemistry",
    "Biology",
    "Chemistry",
    "Computer Science",
    "Dental",
    "Environmental, Earth Sciences",
    "Food, Nutrition, Exercise",
    "General",
    "Geology",
    "Humanitarian Sciences",
    "Mathematics",
    "Optometry",
    "Pharmacy",
    "Physics",
    "Political",
    "Psychology, Philosophy, Therapy",
    "Veterinarian"
  ]
};
